### ISSUE TITLE
Add KALM (Keep / Add / Less / More) retrospective format

### ISSUE THREAD

**Issue by hchevalier** [hchevalier/retrospective#132]

**Comment by coralieco** [comment]
This one really looks like the Starfish format
![image](https://user-images.githubusercontent.com/22852543/115277262-591f3e80-a144-11eb-9679-92bd83684b1d.png)

Not sure it is still relevant :)

**Comment by hchevalier** [comment]
Yes, I guess this is why I didn't implement it, I keep postponing that moment, but you may be right, we can just not implement it 😅

Closing the issue for the moment, thanks for the heads up ;)
