### ISSUE TITLE
404 in the link pending task mail reminder

### ISSUE THREAD

**Issue by Thornolf** [hchevalier/retrospective#258]
Hello,

I got some pending tasks for the retrospective so I received a mail telling me about it : 

<img width="853" alt="image" src="https://user-images.githubusercontent.com/15102389/107929262-b1399900-6f79-11eb-8aff-7e7373d6c1eb.png">

But the link given redirect me to a 404 :

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/15102389/107929369-d5957580-6f79-11eb-82bd-510f5da859e5.png">

The given link is : https://docto-retrospective.herokuapp.com//

Are you aware of this issue ?

**Comment by hchevalier** [comment]
I really should look into Github settings, I received no notification for your issue.

Thanks for noticing, sorry for the time it took to fix that!
