### ISSUE TITLE
Login Error: impossible to connect to my account

### ISSUE THREAD

**Issue by ValentinDewolf** [hchevalier/retrospective#275]
When trying to log in to my account I encountered the following error:

![image](https://user-images.githubusercontent.com/37876093/113110385-4e3d5200-9207-11eb-8096-1385d5b89143.png)

This prevents me from logging in and using the app. This used to work 2 weeks ago

**Comment by hchevalier** [comment]
@ValentinDewolf
I must have broken settings, I never received a notification for this issue, sorry for the inconvenience! I'll try to sort that out as quickly as possible

**Comment by ValentinDewolf** [comment]
@hchevalier No worry,thanks for your answer !

**Comment by hchevalier** [comment]
@ValentinDewolf Does it work if you use the "Sign-in with Google" button just below?

**Comment by ValentinDewolf** [comment]
@hchevalier Tried it on mobile (using safari), it worked using the regular login. I'll try on desktop chrome tomorrow and tell you 👌

**Comment by hchevalier** [comment]
Note for later, can be linked to https://github.com/ReactTraining/react-router/issues/3184#issuecomment-225423781 (navigating to `//`)

**Comment by ValentinDewolf** [comment]
@hchevalier Tested today, no problem at all, I think we can close the issue ?
